---
title: "Untitled"
editor: visual
---
```{r}
# tidy data 
library(tidyverse)
table1
table2
table3

## Spread across two tibbles
table4a  ## cases
table4b
```

```{r}
#pivot longer
table4a |> 
  pivot_longer(cols = c(`1999`, `2000`), 
               names_to = "year", 
               values_to = "cases")
```

```{r}
# pivot wider
table2
table2 |>
    pivot_wider(names_from = type, values_from = count)
```
```{r}
# Separating columns with separate()
table3

table3 |> 
  separate(rate, into = c("cases", "population"))
```

```{r}
table3 |> 
  separate(rate, into = c("cases", "population"), sep = "/")
```
```{r}
table3 |> 
  separate(year, into = c("century", "year"), sep = 2)
```

```{r}
# unite()
table5 |> 
  unite(new, century, year)
  
table5 |> 
  unite(new, century, year, sep = "")
```


```{r}
library(nycflights13)
flights
airlines
airports
planes
weather
```

```{r}
airlines
```

```{r}
# joins 
x <- tribble(
  ~key, ~val_x,
     1, "x1",
     2, "x2",
     3, "x3" )
```

```{r}
# joins 
y <- tribble(
  ~key, ~val_y,
     1, "y1",
     2, "y2",
     4, "y3" )
```

```{r}
#inner join 
x |>
  inner_join(y)
```

```{r}
# left join 
x |>
  left_join(y)
```

```{r}
# right join
x |>
  right_join(y)
```

```{r}
# full join
x |> 
  full_join(y)
```

```{r}
#one to many join 
x <- tribble(
  ~key, ~val_x,
     1, "x1",
     2, "x2",
     2, "x3",
     1, "x4")
```
```{r}
y <- tribble(
  ~key, ~val_y,
     1, "y1",
     2, "y2")

x |> 
  left_join(y)
```

```{r}
# many to many join 
x <- tribble(
  ~key, ~val_x,
     1, "x1",
     2, "x2",
     2, "x3",
     3, "x4" )
```
```{r}
y <- tribble(
  ~key, ~val_y,
     1, "y1",
     2, "y2",
     2, "y3",
     3, "y4" )
x |> 
  left_join(y)
```

```{r}
# defining key columns
flights |> 
  left_join(weather)
  
flights |> 
  left_join(planes, 
            by = "tailnum")
```
```{r}
flights |> 
  left_join(airports, 
            c("dest" = "faa"))
  

```

```{r}

  
flights |> 
  left_join(airports, 
            c("origin" = "faa"))
```


```{r}
xy <- rbind(x,y)
```
```{r}
x1 <- c("Dec", "Apr", "Jan", "Mar")
```
```{r}
x2 <- c("Dec", "Apr", "Jam", "Mar")
sort(x1)
```
```{r}
months <- c(
  "Jan", "Feb", "Mar", "Apr", 
  "May", "Jun", "Jul", "Aug", 
  "Sep", "Oct", "Nov", "Dec")
x1 <- 
  c("Dec", "Apr", "Jan", "Mar")
y1 <- factor(x1, 
             levels = months)
sort(y1)
```
```{r}
x2 <- 
  c("Dec", "Apr", "Jam", "Mar")

y2 <- factor(x2, 
             levels = months)
y2

factor(x1)
```

```{r}
x1
unique(x1)
f1 <- factor(x1, levels = unique(x1))
f1

levels(f1)
```
```{r}
x1 <- c("Dec", "Apr", "Jan", "Mar")

y3 <- 
  factor(x1,
         levels = c("Jan", "Apr", 
                    "Mar", "Dec"),
         labels = c("January", "April",
                    "March", "December"))
y3
```
```{r}
# labels are useful for recoding
x3 <- c(1, 2, 2, 1, 3)

y4 <- factor(x3,
             levels = c(1, 2, 3),
             labels = c("Low", 
                        "Medium", 
                        "High"))
y4
levels(y4)
```

```{r}

gss_cat <- forcats::gss_cat



gss_cat |>
  count(race)
```
```{r}
relig_summary <- gss_cat |>
  group_by(relig) |>
  summarize(
    age = mean(age, na.rm=T),
    tvhours = mean(tvhours,na.rm=T),
    n = n()
  )
```

```{r}
ggplot(relig_summary, 
       aes(tvhours, relig)) + 
  geom_col()
```
```{r}
relig_summary |>
  mutate(relig = [?](relig, tvhours)) |>
  ggplot(aes(tvhours, relig)) + geom_col()
```

```{r}
by_age <- gss_cat |>
  filter(!is.na(age)) |>
  count(age, marital) |>
  group_by(age) |>
  mutate(prop = n / sum(n))

# Default legend order (alphabetical)
ggplot(by_age, aes(x = age, y = prop, color = marital)) +
  geom_line(linewidth = 1) +
  scale_color_brewer(palette = "Set1")

# Legend order follows the line endings at the largest age
ggplot(by_age, aes(x = age, y = prop,
                   color = fct_reorder2(marital, age, prop))) +
  geom_line(linewidth = 1) +
  scale_color_brewer(palette = "Set1") +
  labs(color = "marital")
```
# fct_relevel
```{r}
rincome_summary <- gss_cat |>
  group_by(rincome) |>
  summarize(
    age = mean(age,na.rm=T),
    tvhours = mean(tvhours,na.rm=T),
    n = n()
  )
```

# 
```{r}
ggplot(rincome_summary, 
       aes(age, fct_reorder(rincome, age) ) )  + 
  geom_point()
```

```{r}

ggplot(rincome_summary, 
       aes(age, 
           fct_relevel(rincome, 
               "Not applicable") ) ) +
  geom_point()
```

```{r}
levels(rincome_summary$rincome)
```
```{r}
# str_split()

sentences

sentences|>
head(5) |>
str_split()
```
```{r}
str_length(c("a", "R for data science", NA))
str_c("x", "y", "z")
str_c(c("x", "y", "z"), sep = ", ")
str_c("prefix-", c("a", "b", "c"), "-suffix")
str_c(c("x", "y", "z"), collapse = ", ")
```

```{r}
x <- c("Apple", "Banana", "Pear")
str_sub(x, 1, 3)

## negative numbers count backwards from end
str_sub(x, -3, -1)
```
```{r}
x <- c("apple", "banana", "pear")

str_detect(x, "e")
str_replace(x, "a", "-")
str_replace_all(x, "a", "-")
```

