---
title: "Untitled"
editor: visual
---
# Classwork 11

```{r}
library(tidyverse)
library(rmarkdown)
library(skimr)
library(ggthemes)
library(socviz)
library(geofacet)

install.packages("geofacet")
```
```{r}
climate_opinion_long <- read_csv(
  'https://bcdanl.github.io/data/climate_opinion_2021.csv')
```
```{r}
# Part 1
# Question 1
# Filter climate_opinion_long, so that climate_opinion_long has only estimated percentage of people who think that global warming is caused mostly by human activities.
```

```{r}
library(dplyr)

climate_opinion_long <- climate_opinion_long %>%
  filter(belief == "human")
```

```{r}
# Question 2
# Join the two data.frames, socviz::county_map and the resulting data.frame in Question 1.
socviz::county_map
county_map <- 
  read_csv("https://bcdanl.github.io/data/socviz_county_map.csv")
```
```{r}
library(dplyr)
library(socviz)

```

```{r}
county_map <- 
   read_csv("https://bcdanl.github.io/data/socviz_county_map.csv")
county_map <- county_map %>%
  mutate(id= as.numeric(id))
climate_opinion_human <- climate_opinion_human %>%
  mutate(id=as.numeric(id))

joined_df <- left_join(climate_opinion_human)
```

```{r}
# Question 3 

gop_p <- ggplot(
  data = county_climate,
  mapping = aes(x = long, y = lat,
                fill = belief,
                group = group))

gop_p1 <- gop_p + 
  geom_polygon(color = "gray70", size = 0.05) +
  coord_equal()

gop_p1
```

