---
title: "Untitled"
editor: visual
---

# Part 1. Premier League Soccer

```{r}
#Q1a.
# Create the following two data.frames, tott_home and tott_away:

#tott_home includes all the observations whose HomeTeam is “Tottenham”.
#tott_home includes only the two variables, FTR and HTR.
#tott_away includes all the observations whose AwayTeam is “Tottenham”.
#tott_away includes only the two variables, FTR and HTR.

uk_soccer <- read_csv("https://bcdanl.github.io/data/premier_league_2022.csv")

rmarkdown::paged_table(uk_soccer)

```
```{r}
rmarkdown::paged_table(tott_home) 
```
```{r}
rmarkdown::paged_table(tott_away) 
```
# Q1a
```{r}
tott_home <- uk_soccer |>
  filter(HomeTeam == "Totterham") |>
  select(FTR, HTR)

tott_away <- uk_soccer |>
  filter(AwayTeam == "Totterham") |>
  select(FTR, HTR)
```

#Q1b
```{r}
home_htr <- tott_home |>
  count(HTR)

home_ftr <- tott_home |>
  count(FTR)

away_htr <- tott_away |>
  count(HTR)

away_ftr <- tott_away |>
  count(FTR)

```

#Q1c
```{r}
home_results <- cbind(home_ftr,
                      home_htr)
colnames(home_results) <- c("result", "FTR", "tmp", "HTR")

home_results <- home_results |>
  mutate(tott_location = "Home",
    .before = 0) |>
  select(-HTR) |>
 
  
```
 
 
