# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SWvCJhToZxxlWL3n89HSQnrjPUSQrZki

---
title: "Habits"
author: YOUR_NAME
date: January 27, 2025
format:
  html
---
"""

